CDCgov/cdc-react

.github/workflows/gh_pages.yml
.gitignore
package.json
yarn.lock

This PR adds a GitHub Action workflow script to build/deploy the StorybookJS GitHub page on merges to main.

Added StorybookJS GitHub page build/deploy code within GitHub action workflow

---

thanks.md

@sublettk @ian-sawyer @cfarmer-fearless please review when you get a chance!

remove irrelevant names in thanks.md

---

.github/workflows/pr_checks.yml

Creates a github action to run the component library unit tests using vitest.

PORTAL-393

---

.github/workflows/format.yml
.github/workflows/lint.yml
.github/workflows/unit_test.yml

Github actions for Lint and format checking on PR.

Portal 966/lint pr check

---

package.json
src/components/Button/Button.scss
src/components/Divider/Divider.tsx
src/components/Icon/Icon.tsx
src/components/ProfileHeader/ProfileHeader.scss
src/components/ProfileHeader/ProfileHeaderLogo/ProfileHeaderLogo.scss
src/components/ProfileHeader/ProfileHeaderMenuItem/ProfileHeaderMenuItem.scss
src/components/ProfileHeader/ProfileHeaderPopupMenuItem/ProfileHeaderPopupMenuItem.scss
src/components/Sidebar/Sidebar.scss
src/components/Sidebar/SidebarSection/SidebarSection.scss
src/components/index.ts
src/scss/global.scss
src/stories/Divider.stories.tsx
src/stories/ProfileHeader.stories.tsx

- Adds `Divider` component
- Converts base `font-size` to `17px` to correlate to design documents
- Updates previous rem values accordingly

Divider component, rem defaults

---

package.json
src/components/ProfileHeader/ProfileHeader.scss
src/components/ProfileHeader/ProfileHeaderPopupMenuItem/ProfileHeaderPopupMenuItem.scss
src/components/Sidebar/Sidebar.scss

- Sidebar style updates
- Popup menu style updates

Minor style updates

---

README.md
packages/cdc-react-icons/README.md
packages/cdc-react/.storybook/preview.ts
packages/cdc-react/README.md
packages/cdc-react/src/stories/Icon.stories.tsx
packages/cdc-react/src/stories/storybook.css

Readme docs for root, cdc-react, and cdc-react-icon.  Also adds labels to the icon storybook page.

Portal 1043/readme docs

---

packages/cdc-react/package.json
packages/cdc-react/src/components/Card/Card.scss
packages/cdc-react/src/components/Card/Card.tsx
packages/cdc-react/src/components/index.ts
packages/storybook/src/stories/Card.stories.tsx

An addendum roll-forward of the Card Component feature pull request. Introduces changes to storybook, customizable and theming card props, and manual version bumping.

Portal-998/Card Component Roll-Foward Fixes

---

packages/cdc-react/src/@types/index.ts
packages/cdc-react/src/components/Button/Button.scss
packages/cdc-react/src/components/Button/Button.tsx
packages/cdc-react/src/components/index.ts
packages/cdc-react/src/scss/_mixins.scss
packages/storybook/src/stories/Button.stories.tsx

- Adds primary/tertiary color palette stories for button component
- Consolidates prior stories for button component

PORTAL-995: Add Primary/Tertiary Color Palette stories for Button Component 

---

packages/cdc-react/src/components/Sidebar/Sidebar.scss

A couple spacing bugs were found in the sidebar component.  This PR addresses them and gets the sidebar in a better place.  We can update the versions of the cdc react and icon dependencies in the portal project after this is deployed.

PORTAL-1123

---

packages/cdc-react/src/components/Sidebar/Sidebar.test.tsx
packages/cdc-react/src/tests/mediaQueryUtils.ts

This PR introduces the initial tests for testing for responsiveness using media query mocks.

Portal 968: Init Media Query Tests

---

packages/cdc-react-icons/src/components/ChevronDoubleDown.tsx
packages/cdc-react-icons/src/components/ChevronDoubleUp.tsx
packages/cdc-react-icons/src/components/ChevronLeft.tsx
packages/cdc-react-icons/src/components/ChevronRight.tsx
packages/cdc-react-icons/src/components/index.ts
packages/storybook/src/stories/Icon.stories.tsx

This PR introduces 4 new icons.
- Icons are created as individual components in the cdc-react-icons package. 
- Storybook is also updated to include the new icons.

Portal 1035/add new icons

---

packages/cdc-react-icons/src/components/Bell.tsx
packages/cdc-react-icons/src/components/Person.tsx
packages/cdc-react-icons/src/components/SquareHalfArrowRight.tsx
packages/cdc-react-icons/src/components/Star.tsx
packages/cdc-react-icons/src/components/ZigZag.tsx
packages/cdc-react-icons/src/components/index.ts
packages/cdc-react/src/components/Button/Button.test.tsx
packages/storybook/src/stories/Button.stories.tsx
packages/storybook/src/stories/Icon.stories.tsx
packages/storybook/src/stories/ProfileHeader.stories.tsx
packages/storybook/src/stories/Sidebar.stories.tsx

This PR updates the name of particular icons in Storybook. The icon names will now reflect form not usage.

Portal-1072 - Update icon naming in Storybook

---

packages/cdc-react-icons/src/components/index.ts
packages/cdc-react/src/components/Dropdown/Dropdown.scss
packages/cdc-react/src/components/Dropdown/Dropdown.test.tsx
packages/cdc-react/src/components/Dropdown/Dropdown.tsx
packages/cdc-react/src/components/index.ts
packages/cdc-react/src/scss/_colors.scss
packages/storybook/src/stories/Dropdown.stories.tsx

- Introduces a new UI component called the Dropdown component
- Tests added for component
**Future Improvements:**
Allow tabbing and enter key down to select dropdown items

Portal-1135: Dropdown UI Component

---

packages/cdc-react/src/@types/index.ts
packages/cdc-react/src/components/Pill/Pill.scss
packages/cdc-react/src/components/Pill/Pill.test.tsx
packages/cdc-react/src/components/Pill/Pill.tsx
packages/cdc-react/src/components/index.ts
packages/cdc-react/src/scss/_colors.scss
packages/cdc-react/src/scss/_mixins.scss
packages/cdc-react/src/scss/_palettes.scss
packages/storybook/src/stories/Modal.stories.tsx
packages/storybook/src/stories/Pill.stories.tsx

This is a new component following this figma design: https://www.figma.com/file/TrW6WMf6GYgscPkVQaiMZ0/CDC-React-Components?node-id=1762%3A6810&mode=dev
Still TODO:
- Inverse colors (done)
- Use Sass vars for colors (done)
- Props for text/icon color and background color (done)
- Aria label prop (is this different from SR text prop?) (done)

feat: Portal 1138/pill component

---

packages/cdc-react/src/components/Table/TablePagination/TablePagination.scss
packages/cdc-react/src/components/Table/TablePagination/TablePagination.test.tsx
packages/cdc-react/src/components/Table/TablePagination/TablePagination.tsx
packages/cdc-react/src/components/index.ts
packages/storybook/src/stories/Table.stories.tsx

- This pr adds pagination to the table component
- Please review locally in storybook

Portal-1146: Table Pagination

---

packages/cdc-react/src/components/Checkbox/Checkbox.scss
packages/cdc-react/src/components/Checkbox/Checkbox.test.tsx
packages/cdc-react/src/components/Checkbox/Checkbox.tsx
packages/cdc-react/src/components/index.ts
packages/storybook/src/stories/Checkbox.stories.tsx

This PR introduces a new component: the checkbox. The checkbox is used alongside a label that when clicked, toggles the state of the checkbox. This component also allows an optional description for the checkbox label to further expand context on usage.

Portal 1156/checkbox component

---

packages/storybook/src/stories/Checkbox.stories.tsx

This PR fixes the state of a storybook story for the checkbox component.

Storybook Fix for Checkbox Component

---

packages/cdc-react-icons/src/components/File.tsx
packages/cdc-react-icons/src/components/index.ts

Created the `File` icon that is necessary for the DetailsModal via Figma.

Added the file icon

---

packages/cdc-react/src/components/Alert/Alert.tsx
packages/cdc-react/src/components/Card/Card.tsx
packages/cdc-react/src/components/Checkbox/Checkbox.tsx
packages/cdc-react/src/components/Divider/Divider.tsx
packages/cdc-react/src/components/Dropdown/Dropdown.tsx

* Updates components to allow passing `className` as prop
* `Alert`
* `Card`
* `Checkbox`
* `Divider`
* `Dropdown`

Portal 1534 external classes

---

packages/cdc-react/src/components/Sidebar/Sidebar.test.tsx
packages/cdc-react/src/components/Sidebar/Sidebar.tsx

Adds descriptive aria-label for sidebar button, adds aria-expanded to button that controls sidebar

Adds descriptive aria-label for sidebar button, adds aria-expanded to button that controls sidebar

---

packages/cdc-react/src/components/Dropdown/Dropdown.scss
packages/cdc-react/src/components/Dropdown/Dropdown.tsx
packages/storybook/src/stories/Dropdown.stories.tsx

Connected to this ticket: https://cdc-dexops.atlassian.net/browse/PORTAL-1674
- added static label (label doesn't go away after selection
- added helper text
- added default value

Dropdown fix
